### ISSUE TITLE
Invalid option -c ?

### ISSUE THREAD

**Issue by ratnose** [omry/snapdump#1]
Hello!
I found this awesome app and I installed it via pip3 to my machine.
snapdump -V says: v1.4.3
I have made a config-file.
I run this:
snapdump -c .config/snapdumpconfig.yml backup
This error appears:
snapdump: invalid option -- 'c'
Try `snapdump --help' for more information.

Ehhh what now?

**Comment by omry** [comment]
Looks like you have something else there with the same name:

```
(hydra38) omry@dev$ pip install snapdump
...
Successfully installed snapdump-1.0.7
omry@dev $ snapdump -v
snapdump 1.0.7
(hydra38) omry@dev$ snapdump -V
usage: snapdump [-h] [-v] [--cron] [--conf CONF] {backup,restore,list,cleanup,verify} ...
snapdump: error: unrecognized arguments: -V
```

**Comment by omry** [comment]
Closing, reopen if you need more help.
